name 'ianunruh-skyline'
version '3.0.4'
source 'git://github.com/ianunruh/puppet-skyline'
author 'Ian Unruh'
license 'MIT'
summary 'Skyline Module'
description 'Module for installing Skyline, part of the Etsy Kale stack'
project_page 'https://github.com/ianunruh/puppet-skyline'

dependency 'puppetlabs/stdlib', '>= 4.0.0'
